// index.ts
import { Observable } from '@nativescript/core';

// The native Android bridge is auto-generated by NativeScript.
// If you use react-native, replace the import with your own NativeModule.
declare const com: any;

export interface ConnectionResult {
  readonly ok: boolean;
  readonly message: string;
}

/**
 * Async wrapper around the native Android task.
 * Resolves when the native coroutine/AsyncTask finishes.
 */
export function connectAsync(): Promise<ConnectionResult> {
  return new Promise((resolve, reject) => {
    // The package `com.example.myapp` must match the Kotlin file below.
    const bridge = new com.example.myapp.NativeBridge();

    // The native method takes two lambdas: onSuccess and onError
    bridge.connectAsync(
      new com.example.myapp.NativeBridge.ResultCallback({
        onSuccess: (msg: string) => resolve({ ok: true, message: msg }),
        onError: (err: string) => reject(new Error(err)),
      })
    );
  });
}

/* ---------- demo usage ---------- */
connectAsync()
  .then(res => console.log('Connected:', res.message))
  .catch(err => console.error('Failed:', err.message));
// app/src/main/java/com/example/myapp/NativeBridge.kt
package com.example.myapp

import android.os.Handler
import android.os.Looper
import kotlinx.coroutines.*
import java.util.concurrent.atomic.AtomicBoolean

class NativeBridge {

    interface ResultCallback {
        fun onSuccess(message: String)
        fun onError(error: String)
    }

    private val mainHandler = Handler(Looper.getMainLooper())
    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    /**
     * Mimics the old AsyncTask behaviour:
     * 1. Runs on IO thread
     * 2. Returns result on Main thread
     * 3. Cancels cleanly
     */
    fun connectAsync(callback: ResultCallback) {
        scope.launch {
            try {
                // Simulate long-running work (e.g. HTTP, BLE, Socket)
                val result = doFakeWork()

                withContext(Dispatchers.Main) {
                    callback.onSuccess(result)
                }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    callback.onError(e.message ?: "Unknown error")
                }
            }
        }
    }

    private suspend fun doFakeWork(): String {
        delay(1500) // imitate latency
        if (AtomicBoolean().also { it.set(true) }.get()) {
            return "Android async task finished"
        } else {
            throw RuntimeException("Random failure")
        }
    }
}
